export const STICKY_COLORS = [
  {
    id: 'yellow',
    name: 'Yellow',
    bg: 'bg-[#FEF9C3]',
    headerBg: 'bg-[#FDE047]',
    textColor: 'text-neutral-900',
    borderColor: 'border-neutral-900',
    accentDot: 'bg-[#FACC15]',
  },
  {
    id: 'green',
    name: 'Mint Green',
    bg: 'bg-[#DCFCE7]',
    headerBg: 'bg-[#BBF7D0]',
    textColor: 'text-neutral-900',
    borderColor: 'border-neutral-900',
    accentDot: 'bg-[#4ADE80]',
  },
  {
    id: 'blue',
    name: 'Sky Blue',
    bg: 'bg-[#E0F2FE]',
    headerBg: 'bg-[#BAE6FD]',
    textColor: 'text-neutral-900',
    borderColor: 'border-neutral-900',
    accentDot: 'bg-[#38BDF8]',
  },
  {
    id: 'pink',
    name: 'Rose Pink',
    bg: 'bg-[#FCE7F3]',
    headerBg: 'bg-[#FBCFE8]',
    textColor: 'text-neutral-900',
    borderColor: 'border-neutral-900',
    accentDot: 'bg-[#F472B6]',
  },
  {
    id: 'purple',
    name: 'Lavender',
    bg: 'bg-[#F3E8FF]',
    headerBg: 'bg-[#E9D5FF]',
    textColor: 'text-neutral-900',
    borderColor: 'border-neutral-900',
    accentDot: 'bg-[#C084FC]',
  },
  {
    id: 'classic',
    name: 'Classic OS',
    bg: 'bg-[var(--os-bg)]',
    headerBg: 'bg-[var(--os-fg)]/10',
    textColor: 'text-[var(--os-fg)]',
    borderColor: 'border-[var(--os-border)]',
    accentDot: 'bg-[var(--os-fg)]',
  },
  {
    id: 'dark',
    name: 'Dark Invert',
    bg: 'bg-[#18181B]',
    headerBg: 'bg-[#27272A]',
    textColor: 'text-neutral-100',
    borderColor: 'border-neutral-600',
    accentDot: 'bg-neutral-800',
  },
]

export const INITIAL_STICKY_NOTES = [
  {
    id: 'sticky-welcome',
    text: '📌 Stickies on Desktop!\n\n• Drag the top bar to move me anywhere.\n• Click [+] for a new sticky note.\n• Resize from bottom-right corner.\n• Click ••• to change pastel paper color!',
    color: 'yellow',
    x: 80,
    y: 80,
    width: 230,
    height: 230,
    zIndex: 10,
    isPinned: false,
    updatedAt: Date.now(),
  },
]
