export const DEVELOPER_PROFILE = {
  name: 'Arif Rohman Hakim',
  handle: 'arifrohmanhakim',
  role: 'Fullstack Software Engineer & System Architect',
  location: 'Yogyakarta, Indonesia',
  avatarUrl: '/arif-avatar.jpg',
  website: 'https://arifrohmanhakim.com',
  github: 'https://github.com/arifrohmanhakim',
  linkedin: 'https://www.linkedin.com/in/arif-rohman-hakim/',
  bio: 'Passionate software engineer building resilient web applications, responsive cross-platform mobile apps, and interactive retro-modern computing systems.',
  stats: {
    publicRepos: 13,
    gists: 5,
    experienceYears: '4+ Years',
    focus: 'Fullstack Web & Mobile',
  },
  skills: [
    {
      category: 'Frontend Engineering',
      items: [
        { name: 'React 19 / Next.js', level: 92, tag: 'Advanced' },
        { name: 'TypeScript / JavaScript (ESNext)', level: 90, tag: 'Advanced' },
        { name: 'React Native (Cross-Platform Mobile)', level: 86, tag: 'Proficient' },
        { name: 'Tailwind CSS & UI Architecture', level: 95, tag: 'Mastery' },
        { name: 'Vite & Modern Frontend Tooling', level: 88, tag: 'Advanced' },
      ],
    },
    {
      category: 'Backend & API Engineering',
      items: [
        { name: 'Node.js & Express Ecosystem', level: 88, tag: 'Advanced' },
        { name: 'PHP & Laravel Framework', level: 85, tag: 'Advanced' },
        { name: 'RESTful APIs & GraphQL Endpoints', level: 90, tag: 'Advanced' },
        { name: 'Authentication & Security (OAuth/JWT)', level: 84, tag: 'Proficient' },
      ],
    },
    {
      category: 'Database & Storage Systems',
      items: [
        { name: 'PostgreSQL & MySQL Relational DB', level: 88, tag: 'Advanced' },
        { name: 'SQLite & Client VFS / IndexedDB', level: 92, tag: 'Advanced' },
        { name: 'Redis Cache & State Management', level: 82, tag: 'Proficient' },
      ],
    },
    {
      category: 'DevOps, Systems & Tooling',
      items: [
        { name: 'Docker & Containerization', level: 82, tag: 'Proficient' },
        { name: 'Git & GitHub Actions CI/CD', level: 90, tag: 'Advanced' },
        { name: 'Linux / POSIX Shell Scripting', level: 86, tag: 'Advanced' },
        { name: 'System Architecture & Design Patterns', level: 88, tag: 'Advanced' },
      ],
    },
  ],
  projects: [
    {
      id: 'payaman-os',
      title: 'Payaman OS',
      tagline: 'Retro Monochrome Web Desktop OS',
      description: 'Web-based interactive desktop operating system with virtual file system, vintage apps suite, music streaming, and customizable themes.',
      tech: ['React 19', 'Tailwind CSS', 'Web Audio API', 'xterm.js'],
      githubUrl: 'https://github.com/arifrohmanhakim/Payaman-OS',
      featured: true,
    },
    {
      id: 'bebaslepas',
      title: 'bebaslepas',
      tagline: 'Financial Freedom Leveling Tracker',
      description: 'Wealth tracking and financial independence milestone calculator designed for personal asset progression and budgeting.',
      tech: ['React', 'TypeScript', 'Tailwind CSS'],
      githubUrl: 'https://github.com/arifrohmanhakim/bebaslepas',
      featured: true,
    },
    {
      id: 'doit',
      title: 'doit',
      tagline: 'Simple Digital Wallet',
      description: 'Digital wallet prototype featuring clean transactional UX, instant balance calculations, and history audits.',
      tech: ['TypeScript', 'React Native', 'State Engine'],
      githubUrl: 'https://github.com/arifrohmanhakim/doit',
      featured: true,
    },
    {
      id: 'komikku-api',
      title: 'komikku-api',
      tagline: 'Manga & Comic Reader REST API',
      description: 'Fast, lightweight scraping and content delivery REST API for Bahasa Indonesia comic readers.',
      tech: ['Node.js', 'Express', 'Web Scraping'],
      githubUrl: 'https://github.com/arifrohmanhakim/komikku-api',
      featured: true,
    },
    {
      id: 'payaman_db',
      title: 'payaman_db',
      tagline: 'Terminal SQL Client & Query IDE',
      description: 'Terminal-based SQL query engine interface and database explorer inspired by modern TUI tools.',
      tech: ['Python / TUI', 'SQL', 'Harlequin Architecture'],
      githubUrl: 'https://github.com/arifrohmanhakim/payaman_db',
      featured: false,
    },
    {
      id: 'react-easy-query-builder',
      title: 'react-easy-query-builder',
      tagline: 'Visual Dynamic SQL Query Filter',
      description: 'Modular React UI component allowing users to construct complex conditional filter trees with ease.',
      tech: ['React', 'TypeScript', 'npm package'],
      githubUrl: 'https://github.com/arifrohmanhakim/react-easy-query-builder',
      featured: false,
    },
    {
      id: 'rn-web-maps',
      title: 'rn-web-maps',
      tagline: 'Cross-Platform React Native Web Maps',
      description: 'Interactive map viewer component unified across React Native iOS, Android, and Web.',
      tech: ['React Native', 'Leaflet / OSM', 'JavaScript'],
      githubUrl: 'https://github.com/arifrohmanhakim/rn-web-maps',
      featured: false,
    },
    {
      id: 'system-design-101',
      title: 'System Design 101',
      tagline: 'Architectural Patterns & Interview Guide',
      description: 'Visual diagrams and intuitive explanations of scalable systems, distributed caches, and microservices.',
      tech: ['Architecture', 'Distributed Systems', 'Engineering'],
      githubUrl: 'https://github.com/arifrohmanhakim/system-design-101',
      featured: false,
    },
  ],
}
