export const PET_SPECIES = [
  {
    id: 'cat',
    name: 'Neko Cat',
    subtitle: 'Playful & Curious Feline',
    icon: '🐱',
    soundPitch: 920,
    favoriteFood: 'Fresh Fish 🐟',
    phrases: [
      'Meow~',
      'Purr purr...',
      'Feed me fish! 🐟',
      'Scratch behind my ears? ❤️',
      'Napping time... 💤',
      'Chasing the mouse cursor! 🐾',
      'Payaman OS is cozy!',
    ],
    defaultX: 280,
    defaultY: 480,
  },
  {
    id: 'dog',
    name: 'Shiba Dog',
    subtitle: 'Loyal & Energetic Pup',
    icon: '🐶',
    soundPitch: 640,
    favoriteFood: 'Juicy Bone 🍖',
    phrases: [
      'Woof woof!',
      'Wagging tail! 🐾',
      'Let’s play fetch! 🎾',
      'Good human! ❤️',
      'Bork! What are we coding?',
      'Ready for adventure!',
      'Best desk buddy ever!',
    ],
    defaultX: 360,
    defaultY: 480,
  },
  {
    id: 'duck',
    name: 'Quacky Duck',
    subtitle: 'Bubbly Desktop Companion',
    icon: '🦆',
    soundPitch: 780,
    favoriteFood: 'Sweet Bread 🍞',
    phrases: [
      'Quack quack!',
      'Waddling around~ 💦',
      'Did someone say debug duck?',
      'Quack! Tell me your bugs!',
      'Splashing in puddles! 🦆',
      'All code looks good to me!',
    ],
    defaultX: 200,
    defaultY: 480,
  },
  {
    id: 'frog',
    name: 'Hopper Frog',
    subtitle: 'Zen & Chill Amphibian',
    icon: '🐸',
    soundPitch: 520,
    favoriteFood: 'Yummy Flies 🪰',
    phrases: [
      'Ribbit!',
      'Hop hop! 🌿',
      'Catching bugs in your code! 🪲',
      'Croak... peaceful day.',
      'Water lily vibes ✨',
      'Staying zen on your desktop.',
    ],
    defaultX: 440,
    defaultY: 480,
  },
  {
    id: 'hamster',
    name: 'Puffy Hamster',
    subtitle: 'Tiny Cheerful Nibbler',
    icon: '🐹',
    soundPitch: 1050,
    favoriteFood: 'Sunflower Seeds 🌻',
    phrases: [
      'Squeak squeak!',
      'Munching sunflower seeds! 🌻',
      'My cheeks are super puffy!',
      'Running on the virtual wheel! ⚡',
      'Tiny but full of energy!',
      'So cozy in here!',
    ],
    defaultX: 520,
    defaultY: 480,
  },
]

export const PET_TREATS = [
  { id: 'fish', name: 'Fresh Fish', icon: '🐟', nutrition: 35, happiness: 20 },
  { id: 'bone', name: 'Tasty Bone', icon: '🍖', nutrition: 35, happiness: 20 },
  { id: 'seed', name: 'Sunflower Seeds', icon: '🌻', nutrition: 25, happiness: 15 },
  { id: 'berry', name: 'Sweet Strawberry', icon: '🍓', nutrition: 20, happiness: 25 },
  { id: 'cheese', name: 'Golden Cheese', icon: '🧀', nutrition: 30, happiness: 20 },
]

export const PET_TOYS = [
  { id: 'ball', name: 'Bouncy Ball', icon: '🎾', fun: 30, energyCost: 15 },
  { id: 'yarn', name: 'Yarn Ball', icon: '🧶', fun: 35, energyCost: 10 },
  { id: 'laser', name: 'Laser Beam', icon: '✨', fun: 40, energyCost: 20 },
  { id: 'music', name: 'Tiny Jukebox', icon: '🎵', fun: 25, energyCost: 5 },
]
