export const PET_SPECIES = [
  {
    id: 'cat',
    name: 'Neko Cat',
    subtitle: 'Playful & Curious Feline',
    iconType: 'cat',
    soundPitch: 920,
    favoriteFood: 'Fresh Fish',
    phrases: [
      'Meow~',
      'Purr purr...',
      'Feed me fish!',
      'Scratch behind my ears?',
      'Napping time...',
      'Chasing the mouse cursor!',
      'Payaman OS is cozy!',
    ],
    defaultX: 280,
    defaultY: 480,
  },
  {
    id: 'dog',
    name: 'Shiba Dog',
    subtitle: 'Loyal & Energetic Pup',
    iconType: 'dog',
    soundPitch: 640,
    favoriteFood: 'Juicy Bone',
    phrases: [
      'Woof woof!',
      'Wagging tail!',
      'Let’s play fetch!',
      'Good human!',
      'Bork! What are we coding?',
      'Ready for adventure!',
      'Best desk buddy ever!',
    ],
    defaultX: 360,
    defaultY: 480,
  },
  {
    id: 'duck',
    name: 'Quacky Duck',
    subtitle: 'Bubbly Desktop Companion',
    iconType: 'duck',
    soundPitch: 780,
    favoriteFood: 'Sweet Bread',
    phrases: [
      'Quack quack!',
      'Waddling around~',
      'Did someone say debug duck?',
      'Quack! Tell me your bugs!',
      'Splashing in puddles!',
      'All code looks good to me!',
    ],
    defaultX: 200,
    defaultY: 480,
  },
  {
    id: 'frog',
    name: 'Hopper Frog',
    subtitle: 'Zen & Chill Amphibian',
    iconType: 'frog',
    soundPitch: 520,
    favoriteFood: 'Yummy Flies',
    phrases: [
      'Ribbit!',
      'Hop hop!',
      'Catching bugs in your code!',
      'Croak... peaceful day.',
      'Water lily vibes.',
      'Staying zen on your desktop.',
    ],
    defaultX: 440,
    defaultY: 480,
  },
  {
    id: 'hamster',
    name: 'Puffy Hamster',
    subtitle: 'Tiny Cheerful Nibbler',
    iconType: 'hamster',
    soundPitch: 1050,
    favoriteFood: 'Sunflower Seeds',
    phrases: [
      'Squeak squeak!',
      'Munching sunflower seeds!',
      'My cheeks are super puffy!',
      'Running on the virtual wheel!',
      'Tiny but full of energy!',
      'So cozy in here!',
    ],
    defaultX: 520,
    defaultY: 480,
  },
]

export const PET_TREATS = [
  { id: 'fish', name: 'Fresh Fish', iconType: 'fish', nutrition: 35, happiness: 20 },
  { id: 'bone', name: 'Tasty Bone', iconType: 'bone', nutrition: 35, happiness: 20 },
  { id: 'seed', name: 'Sunflower Seeds', iconType: 'seed', nutrition: 25, happiness: 15 },
  { id: 'berry', name: 'Sweet Strawberry', iconType: 'berry', nutrition: 20, happiness: 25 },
  { id: 'cheese', name: 'Golden Cheese', iconType: 'cheese', nutrition: 30, happiness: 20 },
]

export const PET_TOYS = [
  { id: 'ball', name: 'Bouncy Ball', iconType: 'ball', fun: 30, energyCost: 15 },
  { id: 'yarn', name: 'Yarn Ball', iconType: 'yarn', fun: 35, energyCost: 10 },
  { id: 'laser', name: 'Laser Beam', iconType: 'laser', fun: 40, energyCost: 20 },
  { id: 'music', name: 'Tiny Jukebox', iconType: 'music', fun: 25, energyCost: 5 },
]
